<?php

namespace CGI\GedBundle\Repository;

/**
 * RefProfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefProfilRepository extends \Doctrine\ORM\EntityRepository
{
}
