<?php

namespace CGI\GedBundle\Repository;

/**
 * TblSimulationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TblSimulationRepository extends \Doctrine\ORM\EntityRepository
{
}
