<?php

namespace CGI\GedBundle\Repository;

/**
 * TblUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TblUserRepository extends \Doctrine\ORM\EntityRepository
{
}
